name: audiodream
dependencies:
  - python=3.6.6
  - numpy=1.15.4
  - scipy=1.1.0
  - six=1.11.0
  - jupyter
  - h5py
  - pip:
    - pysoundfile==0.9.0
    - tensorflow==1.3.0
    - resampy==0.2.1
    - keras==2.0.8